#!/bin/bash

#  _   _            _    _____ _          ____            
# | | | | __ _  ___| | _|_   _| |__   ___| __ )  _____  __
# | |_| |/ _` |/ __| |/ / | | | '_ \ / _ \  _ \ / _ \ \/ /
# |  _  | (_| | (__|   <  | | | | | |  __/ |_) | (_) >  < 
# |_| |_|\__,_|\___|_|\_\ |_| |_| |_|\___|____/ \___/_/\_\
#  _____                 _   _                 
# |  ___|   _ _ __   ___| |_(_) ___  _ __  ___ 
# | |_ | | | | '_ \ / __| __| |/ _ \| '_ \/ __|
# |  _|| |_| | | | | (__| |_| | (_) | | | \__ \
# |_|   \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
#
# A bunch of useful functions for hacking on HackTheBox

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
init_file=$script_dir"/.init"

htbhost () {
    ip=$(ip a show tun0 2>/dev/null | grep inet | head -1 | awk '{print $2}' | sed s/...$//)

    if [ -n "$ip" ]; then
        echo $ip
    else
        echo "[-] You Do Not Seem To Be Connected To The VPN..."
	echo
    fi
}

htbtarget () {
    pidof openvpn >/dev/null
    if [ $? -eq 1 ]; then
        echo "[*] OpenVPN Session Not Running..."
        echo
        return 1
    fi

    if [ -n "$1" ]; then
        grep "target" $HOME/.bashrc > /dev/null

        if [ $? -eq 1 ]; then
            echo "target="\"$1\" >> $HOME/.bashrc
        else
            sed -i "s/target=.*/target=\"$1\"/g" $HOME/.bashrc >/dev/null
        fi

        source $HOME/.bashrc
    else
        echo "[!] Please Provide Target IP"
        echo
    fi
}

htbinitfile () {
    if [ -n "$1" ]; then
        if [ -e $1 ]; then
            echo $1 > $init_file
            echo "[*] Init File Path Set"
            echo
         else
             echo "[-] File Does Not Exist..."
             echo
             return 1
         fi
    else
        if [ -e $init_file ]; then
            cat $init_file
        else
            echo "[-] Init File Has Not Been Set..."
            echo
            return 1
        fi
    fi
}

htbinit () {
    pidof openvpn >/dev/null
    if [ $? -eq 1 ]; then
	    if [ -f $init_file ]; then
	        sudo --background openvpn $(cat $init_file) &>/dev/null
	        echo "[*] Initiated Connection..."
	        echo
    	else
	        echo "[-] Set Init File Path..."
	        echo
	    fi
    else
        echo "[-] OpenVPN is Already Running..."
	    echo
        return 1
    fi
}

htbkill () {
    pid=$(pidof openvpn)
    if [ $? -eq 1 ]; then
        echo "[-] No OpenVPN Session Running..."
        echo
        return 1
    else
        echo "[*] Killing OpenVPN PID: $pid"
        sudo kill -SIGKILL $pid
        echo

        delete=$(egrep 'target="([0-9]{1,3}\.){3}[0-9]{1,3}"' $HOME/.bashrc)
        if [ $? -eq 0 ]; then
            sed -i "/$delete/d" $HOME/.bashrc
            target=""
            source $HOME/.bashrc
        fi
    fi
}
